### ISSUE TITLE
Assertion failure in -[_ASCollectionViewProxy forwardingTargetForSelector:]

### ISSUE THREAD

**Issue by StrauneanuDimitri** [nguyenhuy/AsyncMessagesViewController#4] opened 2015-11-27 16:12 UTC
Hi! Here is the scenario: my first view controller has an ASTableView containing some dummy cells for testing. Clicking either cell will push a new view controller named ChatViewController (which is exactly the ViewController from your example), with the exception that the collectionView scrolls to bottom after all the messages are inserted with success.

```
dataSource.collectionView(collectionView, insertMessages: messages) { (success) -> () in
            if (success) {
                self.scrollCollectionViewToBottom()
            }
        }
```

After I click the back button, my app crashes giving this log:
![screen shot 2015-11-27 at 17 58 21](https://cloud.githubusercontent.com/assets/6670019/11445110/37d0c5c4-9532-11e5-8fb6-b14932d1c513.png)

If I scroll back to top in the ChatViewController and click the back button, the app will not crash. Is there any solution? Thank you!

**Comment by nguyenhuy** [comment] 2015-12-01 19:04
@StrauneanuDimitri Thanks for trying out this library and reporting this issue. If you press the back button while the collection view is still scrolling, the view will stop scrolling and try to notify its delegate, which has already been deallocated. Thus, a crash occurs. 

Could you try to manually set the collection view's delegate to nil right before the delegate itself is deallocated? In my example, ViewController is a (dummy) ASCollectionViewDelegate, so this piece of code in `ViewController.swift` should work:

``` swift
    deinit {
        collectionView.asyncDelegate = nil
    }
```

**Comment by nguyenhuy** [comment] 2015-12-01 19:16
P/S: I believe the problem is caused by ASDK itself (https://github.com/facebook/AsyncDisplayKit/issues/721) and should be fixed once https://github.com/facebook/AsyncDisplayKit/pull/790 is landed. Until then, we need to nil a **weak** reference ourselves :(

**Comment by StrauneanuDimitri** [comment] 2015-12-02 16:18
Yes, it's working now. Much appreciated for that code. This is a fantastic library!

**Comment by nguyenhuy** [comment] 2015-12-02 16:24
Really happy to know! I will keep you posted regarding the ASDK issue and its fix.

**Comment by xumeng** [comment] 2016-01-29 04:48
Thanks, It's helpful!

**Closed as completed** 2017-01-17 16:40 UTC
